### ISSUE TITLE
Editing the SASS files

### ISSUE THREAD

**Issue by munkii** [tolbxela/ASP.NET-Core-UI-Free-Admin-Template#1]
We've used your ASP.NET Core template, so many thanks.

If we want to edit the CoreUI theme it lokks liuke we should be editing the _custom.scss and _variables.scss files. Is that correct?
Why are there two CoreUI folders under "wwwroot"? One in "wwwroot" and one in "wwwroot/lib"

**Comment by tolbxela** [comment]
Hi munkii,
it's nice to hear! 
I did not changed the SASS files in my project. I just added some small changes to site.css.
If you change SASS files then you need to compile them to CSS. I have no experience with SASS till now. 
So, I would only chnage CSS myself.
CoreUI in the `wwwroot `folder is for testing purposes. It is the original Core IU Template. You need only the `wwwroot/lib` to make it work.
